Feature/rendszerterv1 7 11 13
markvarga21/wordMatcherBackend pull request #15
Opened 2022-09-14 22:26 UTC by Fradi575

Kész a rendszertervből a részem.

2022-09-14 22:28 UTC, Fradi575 commented
Kész a rendszertervből a részem.

2022-09-15 09:16 UTC, markvarga21 commented on doc/rendszerterv.md
> +tölthetik fel az angol és magyar szópárokat a feladatba.  A rendszer egyaránt elérhető webes felületen, és android környezetben is. Az már nem cél, hogy IOS eszközön fusson. A megoldásra a felhasznál
csak webesen lesz elérhető, androidon és ios-en nem lesz elérhető mert arra külön rendszert kéne fejlesztenünk

2022-09-15 09:16 UTC, markvarga21 commented on doc/rendszerterv.md
> +* Fogalmak:
Itt JSF-et fogunk használni végül, mert az egyszerűbb, nem pedig HTML+CSS+JS -et

2022-09-15 09:18 UTC, markvarga21 commented on doc/rendszerterv.md
> +Böngészők: Google Chrome , Mozilla Firefox, Microsoft Edge  Operációs rendszer: Windows 10
Itt jól mutatni egy sortörés is az Operációs rendszerek előtt

2022-09-15 09:18 UTC, markvarga21 commented on doc/rendszerterv.md
> +kell, hogy a jövőben kiadott Android verziókkal kompatibilis-e a program.
Itt mint fentebb említettem is, nem lesz külön Android és IOS, csak webes felület

2022-09-15 09:19 UTC, markvarga21 requested changes
Irtam par kommentet azokat javitsd kerlek

2022-09-15 10:24 UTC, markvarga21 approved these changes
Jo lett, mergelem :D

2022-09-15 10:24 UTC, merged